### ISSUE TITLE
Nodes stuck in protocolinfo/nodeinfo state

### ISSUE THREAD

**Issue by mdegroux** [AlCalzone/node-zwave-js#3743]
Hello,

In a fresh install of zwavejs2mqtt 5.12.0 on docker, with a zwave controller having an existing network

My previous software was runnin openzwave 1.4 and I had custom network key
In zwavejs2mqtt, I have copied the network key in S0 legacy and generated new S2 keys

In the control panel,:
- all electric powered nodes are in nodeinfostate 
- all battery powered nodes (node 18 - fibaro FGMS-001 and node 43 - Secure SRT321) are in protocolinfo state and the manufacturer is unknwon

I have woke up manually my devices but it does nothing

I have attached zwave-js and zwavejs2mqtt logs
[zwavejs_2021-11-17 (1).log](https://github.com/zwave-js/zwavejs2mqtt/files/7550775/zwavejs_2021-11-17.1.log)
[zwavejs2mqtt_2021-11-17 (1).log](https://github.com/zwave-js/zwavejs2mqtt/files/7550776/zwavejs2mqtt_2021-11-17.1.log)

**Comment by robertsLando** [comment]
Looks good on my side, it looks like some commands are dopped but I don't see any errors on first sight on zwavejs side. Let's see @AlCalzone opinion about logs

**Comment by AlCalzone** [comment]
The interview of all nodes is still going on, so you'll need to have a bit of patience. It takes long because several of your nodes reply with incorrectly formatted commands. Those are dropped, leading to timeouts of 10s each (total 390s).

Nodes 23, 47, 49, 50, 54, 58, 67:
- Support Association CC, but reply with a truncated command for the group count (byte X is missing):
![grafik](https://user-images.githubusercontent.com/17641229/142160628-6a58597d-44ec-47df-8246-9ff4af290a51.png)
- Don't include the marked byte in the command list response: 
![grafik](https://user-images.githubusercontent.com/17641229/142160072-b6778f8f-90e4-42e5-871e-36c150f9ae5d.png)
- Respond with association group names where the length value is higher than the name field is long, e.g. 12 for "BasicSetKey" (11 chars):
![grafik](https://user-images.githubusercontent.com/17641229/142160345-c605efad-5fbd-4258-8314-28d119fda324.png)

I guess those are all the same devices?

**Comment by mdegroux** [comment]
Yes, they are all qubino ZMNHJD1

**Comment by mdegroux** [comment]
I don't know if it can helps, I have made tests with zwave2mqtt (not zwave**js**2mqtt)
I have set a command timeout of 5s and the network is ready in few minutes

I have restarted zwavejs2mqtt and I'll wait without touching the configuration

**Comment by AlCalzone** [comment]
AFAIK, OpenZWave relies heavily on the information in their XML config files while Z-Wave JS tries to get as much information as possible from the devices themselves. OZW likely didn't query these commands at all.

Might be worth contacting the Qubino support about this, although this won't help you immediately since AFAIK they only update their devices offline.

**Comment by mdegroux** [comment]
After a long wait (more than an hour) all nodes are in complete state

**Comment by mdegroux** [comment]
A last question,
When migrating from OZW to zwave-js
in OZW, we have only a network key
in zwave-js we have one S0 and three S2

Is it a good practice to copy the OZW key in S0 and generate three random S2?

**Comment by robertsLando** [comment]
> Is it a good practice to copy the OZW key in S0 and generate three random S2?

Yes

> in OZW, we have only a network key

That's because OZW didn't ever supported S2 security
