### ISSUE TITLE
GoControl GC-TBZ48 not working

### ISSUE THREAD

**Issue by jeffarndt** [AlCalzone/node-zwave-js#4103]
With the home assistant update to Zwave JS, my GoControl GC-TBZ48 had lost connectivity. I thought maybe it was batteries, so I replaced them. Then I was able to exclude and re-add it and it worked. 

Today, it lost connection again. I had to factory reset the thermostat and added it again. Now it will not interview properly.

**Comment by AlCalzone** [comment]
Please choose an appropriate issue template (e.g. [bug report](https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=&template=bug_report.yml)) and fill it out completely when opening an issue. That helps us investigate your issue quicker because all the necessary information is there.
