### ISSUE TITLE
Unable to save Location 

### ISSUE THREAD

**Issue by rgerrans** [AlCalzone/node-zwave-js#4734]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

I'm using the Node-Red nodes contributed by @marcus-j-davies  In the version based on v6 I was able to save device name & location for my Zwave devices (though required a page reload to see them). In the v7 version, I now get the error "Node #10 does not support the command NameSet! (ZW0302)"   I am able to get the device name to change but not the location,

Marcus said to report it as a bug here.

What causes the bug?
Editing device name and location (or just location) in Node-Red

What do you observe?
the error "Node #10 does not support the command NameSet! (ZW0302)"   I am able to get the device name to change but not the location,

What did you expect to happen?
Device location to update

  1. Go to 'Zwave' management interface in Node-Red
  2. Click on "edit" for Device
  3. Change Device Name and Location and hit submit

### Device information

Manufacturer:  Eaton
Model name:  Multiple devices tried
Node ID in your network:  10

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [X] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: v7
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

worked in the v6 version

### Attach Driver Logfile

[Zwave_JS.log](https://github.com/zwave-js/node-zwave-js/files/8953538/Zwave_JS.log)

**Comment by marcus-j-davies** [comment]
@AlCalzone,

For reference I do this in the NR module.
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/77c758a72a48c8c154649ecd7028a98e2f0c2f71/zwave-js/zwave-js.js#L983

```javascript
case 'setNodeName':
   NodeCheck(Params[0]);
   Driver.controller.nodes.get(Params[0]).name = Params[1];
   SupportsNN = Driver.controller.nodes
       .get(Params[0])
       .supportsCC(CommandClasses['Node Naming and Location']);
   if (SupportsNN) {
       await Driver.controller.nodes
           .get(Params[0])
           .commandClasses['Node Naming and Location'].setName(Params[1]);
   }
   ReturnNode.id = Params[0];
   Send(ReturnNode, 'NODE_NAME_SET', Params[1], send);
   ShareNodeList();
   break;

case 'setNodeLocation':
   NodeCheck(Params[0]);
   Driver.controller.nodes.get(Params[0]).location = Params[1];
   SupportsNN = Driver.controller.nodes
       .get(Params[0])
       .supportsCC(CommandClasses['Node Naming and Location']);
   if (SupportsNN) {
       await Driver.controller.nodes
           .get(Params[0])
           .commandClasses['Node Naming and Location'].setLocation(
               Params[1]
           );
   }
   ReturnNode.id = Params[0];
   Send(ReturnNode, 'NODE_LOCATION_SET', Params[1], send);
   ShareNodeList();
   break;
```

I have noticed the CC's implementation of `supportsCommand` only includes the Get's
so is passing the check, should it also include the Set's 🤷‍♂️ 

@rgerrans 
> I am able to get the device name to change but not the location

The name is being set, but only locally.
it then moves on to update the device and fails - at this point, I no longer attempt to update  the location, as technically our request has ran into an issue - that we didn't expect, so the UI is stopping anything further from happening, and letting you know what happened.

You can see here, that the UI didn't follow up with setting the location, shortly after you restart the driver (to disable logging I assume)

```
2022-06-22T00:23:46.003Z NDERED « [CONTROLLER] Payload received.
2022-06-22T00:23:46.004Z NDERED « [API: ControllerAPI] [Method: setNodeName]
                                  └─[params]
                                      0: 10
                                      1: Bar Light
2022-06-22T00:23:46.007Z CNTRLR   [Node 010] [~] [Node Naming and Location] name: "Bar Light" => "Bar [internal]
                                   Light"
2022-06-22T00:23:46.008Z NDERED   [ERROR] [INPUT] Node #10 does not support the command NameSet! (ZW0302)
2022-06-22T00:23:58.189Z NDERED   [SHUTDOWN] [RESTART] Cleaning up...
2022-06-22T00:23:58.190Z DRIVER   destroying driver instance...
2022-06-22T00:23:58.256Z DRIVER   driver instance destroyed
pi@Node-RED:/opt/node-red $
```

> in the version based on v6 I was able to save device name & location 

This is actually a good thing I think 🤔 
see in V7, the UI now correctly handles errors, instead of silently just assuming it all went well, its likely never been successful, but the UI previously carried on, even after causing an error, so the location was still being set (locally at least) because it was not aware of the error being returned.

The affect of the change of course, is not being able to fully complete a request, but for certain commands, it's the difference between being all ok and a module crash. 😬

**Comment by AlCalzone** [comment]
> I have noticed the CC's implementation of `supportsCommand` only includes the Get's
> so is passing the check, should it also include the Set's 🤷‍♂️

Ohhh, good catch! I missed this when I looked there last time on mobile.
