### ISSUE TITLE
Yale ZWAVE S2 Module missing manufacturer and lock versions

### ISSUE THREAD

**Issue by vectorcatch** [AlCalzone/node-zwave-js#4843]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Pairing a Yale Lock using the S2 version of the module
What do you observe?
The lock does not display the product and product code correctly. It also appears to fail to retrieve the user codes. The master code is retrieved, but the user codes must be retrieved one at a time. It's also unclear if the door open/closed detection is working correctly in S2.
What did you expect to happen?
The product and info codes to display correctly as well as the user code all be retrieved when refreshing them. 

### Device information

Manufacturer: Yale
Model name: YRM276
Node ID in your network: 10

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[patio_door_s2 (node 10).log](https://github.com/zwave-js/node-zwave-js/files/9186116/patio_door_s2.node.10.log)
[patio_door_s0 (node 11).log](https://github.com/zwave-js/node-zwave-js/files/9186137/patio_door_s0.node.11.log)

**Comment by AlCalzone** [comment]
At first the S2 lock fails to be included with S2 a few times and ends up insecure (so no useful operation).
I'm relatively sure this is a connectivity issue since either the node repeated commands or did not respond at all sometimes.

After it worked, the interview does look good. The "fingerprint" is retrieved, but we don't have a config file for the lock, so it doesn't get identified:
```
manufacturer id: 0x0129
product type:    0x8014
product id:      0x5600
firmware versions: 2.17, 32.0
```
We'll need some more information about the device to add this. Please fill out this [issue template](https://github.com/zwave-js/node-zwave-js/issues/new?assignees=&labels=config+%E2%9A%99&template=device_config.yml&title=Missing+device+configuration%3A+%3Center+manufacturer+and+device+name%3E).

About the user codes: not querying them is intended. We used to query all of them as part of the interview, but this lead to huge issues and interviews that took forever. Theoretically you should be able to query them all at once though by clicking the refresh button next to "User Code CC".
However there seems to be a [bug](https://github.com/zwave-js/node-zwave-js/issues/4845) where this uses a bulk query that your device does not support.

The bugs I found are tracked in https://github.com/zwave-js/node-zwave-js/issues/4845 and https://github.com/zwave-js/node-zwave-js/issues/4844.

I'm going to close this issue in favor of the others.
