### ISSUE TITLE
Investigate xstate memory leak

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#5122]
Everyone, who was having memory leak issues with the Home Assistant addon - please provide an hour or two of driver logs.

**Comment by Mariusthvdb** [comment]
posting half an hour, since my MacBook is starting to fan quite loudly.... log might be growing a bit..

[zwave_js-2.log](https://github.com/zwave-js/node-zwave-js/files/9657313/zwave_js-2.log)

maybe this is already useful, will try to keep it open 

__edit__

and a new one:

[zwave_js-4.log](https://github.com/zwave-js/node-zwave-js/files/9658309/zwave_js-4.log)

**Comment by zener82** [comment]
Here is my log contribution if needed during this night until today 8AM. 

[debugzwavejs.log.txt](https://github.com/zwave-js/node-zwave-js/files/9661890/debugzwavejs.log.txt)

I badly configured to info level instead of debug.
So I've changed it to debug and restart the add-on.

**Comment by spraguej248** [comment]
Log taken after fixes applied.  Thank you!

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/9667686/zwave_js.1.log)

**Comment by AlCalzone** [comment]
Thanks for those logs. I probably won't be able to review them in the near future, but good to have them anyways.

**Comment by AlCalzone** [comment]
Possibly fixed, need to update and test: https://github.com/statelyai/xstate/issues/3616

**Comment by AlCalzone** [comment]
Confirmed fixed
