### ISSUE TITLE
service that emits "info" event for all known nodes

### ISSUE THREAD

**Issue by josh-m-sharpe** [AlCalzone/node-zwave-js#5226]
**Is your feature request related to a problem? Please describe.**

Problem:  I have 30-40 nodes, but only 4-5 different types of devices.  So, like 10 of the same brand/model dimmer switch.  I want to consistently configure them, however, I have no programatic way to get the current list of node IDs for all my dimmer switches.  This means I have to maintain a list of ever-changing node IDs (included/excluded/factory resets all change the node ID)

**Describe the solution you'd like**
I'd like a Zwave Service that triggers the hub to emit a Notification event for every node it knows about.
The Info Notification event would include
- similar things to the current Notification event (which can uniquely identify the node)
- additional information so that I can identify which type of device it is.
-- Something like "Product" or "Product Code" (from the zwave control panel UI) would work.  Or, if those things translate to a unique "device type identifier" that would work too. Anything such that I can then turn around and send different `set_config_parameters` to different types of nodes.
- including firmware version would probably be good too, because who knows parameter numbers might change?

All this data is available in the UI.

**Describe alternatives you've considered**
Maintaining a list of ever changing node IDs gets old

**Additional context**
If this endpoint existed I think building a flow in Node-Red would be pretty straight forward:
1) Trigger new Service
2) Listen for new Info events and then call set_config_parameter as many times I as I want for each different node type.

Cheers! Thanks!

**Comment by AlCalzone** [comment]
I don't see the benefit of adding another way to expose this. Especially since events are meant for things that happen. All the information is available via the `ZWaveNode` class:
- unique IDs -> https://zwave-js.github.io/node-zwave-js/#/api/node?id=manufacturerid-productid-and-producttype
- firmware version -> https://zwave-js.github.io/node-zwave-js/#/api/node?id=firmwareversion
- model name and description (if config file exists) -> https://zwave-js.github.io/node-zwave-js/#/api/node?id=deviceconfig
