### ISSUE TITLE
Message Dead then alive only on all my FGR223

### ISSUE THREAD

**Issue by WorldOfGZ** [AlCalzone/node-zwave-js#6195]
Hello,

I have a strange situation with my Fibaro FGR223. I have 8 modules with all same firmware v5.1
With automation I launch all of them with a delay in Up/Down or positionning.

Every time I have a message on one-two of them (never the same) that the module is dead, and seconds after module is alive.

I upgraded in 8.23.0. It seems appear less than in 8.22.0 but I still have at least 4 messages by days. 

This is only on this module, not on all other modules or brands. Do you know if there a special thing I can do on these FGR223 ?
Thanks

**Comment by memphi2** [comment]
Hello,
I had problems similar to yours with the FGR223 when S2 encryption was enabled. I was able to fix the problem by defining the routes manually and reducing the speed of the route to 40 kbps.  Of course, you can also connect without encryption, but I didn't want to do that with shutters.

**Comment by WorldOfGZ** [comment]
Hello, thanks for your answere.

All are included unsecure, I don't have S2 on my network.
I also checked the route, for me it's seems not strange, only one jump on the two last message. Speed at 100kbps, maybe I can try to reduce.
Btw, how did you assign the routes manually ? Can't find it.
Thanks

**Comment by memphi2** [comment]
In the Network Graph, klick on the node. A window will appear and you can set the priority route and the return route there. Don't forget to click save. Here you can also run the diagnostics.

**Comment by WorldOfGZ** [comment]
Always thinked this page was only cosmetic. My bad...

I made some direct route at 40kbps, in health rating on tested node goes from 3/10 to 7/10.
I will do it for others FGR223 and see in the next automation what's happen

Really thanks for this tip.

**Comment by WorldOfGZ** [comment]
Unfortunatelly, still have these messages, even with node in direct routing with route speed at 40bps.

**Comment by AlCalzone** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

The log should include one of the problematic interactions.

**Comment by WorldOfGZ** [comment]
@AlCalzone No problem, I will do it.
Just to be sure before, should I let the manual route at 40kbps or should I have to go back to automatic route ?
Thanks

**Comment by AlCalzone** [comment]
Doesn't really matter, as long as the problem happens in the logfile.

**Comment by WorldOfGZ** [comment]
Good Evening @AlCalzone 

Please find the log for the automation of this evening.
[zwave-js-ui-store.zip](https://github.com/zwave-js/node-zwave-js/files/12412293/zwave-js-ui-store.zip)

I received messages for node 79
Dead at 19:23:12
Alive at 19:23:14

Hope it can help. Thanks

Edit: I would also add that cover in node 79 shut down correctly.

**Comment by AlCalzone** [comment]
This has the typical signs of bad signal strength:
- Most RSSI measurements on the controller are around -90 dBm, which is pretty close to background noise. Some repeaters report much better values (around -60/-70), so this seems to be an issue with the controller range.
- Lots of incoming commands are repeated, again hinting at a suboptimal controller range. This happens when devices don't get the acknowledgement that their commands were received.
- Some outgoing commands fail with status `transmit status: Fail, took 0 ms`, which means the controller is jammed and cannot transmit (due to the above)
- Only around 30 of the ~600 outgoing commands succeeded with 100 kbit/s, most need 40 or even 9.6 kbit/s. Several commands have delays upwards of 1-10 seconds.

Work through these links if you haven't already:
1. https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting
2. If there are still issues afterwards: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=testing-the-connection-strength
3. Always a good idea: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=optimizing-the-reporting-configuration

Also, which Z-Wave stick do you have?

**Comment by WorldOfGZ** [comment]
Thanks for your time. 
My stick is a Zooz 700 Series Z-Wave Plus in v7.18.3

Currently it is in direct connection to the Nuc. I will try with a extension cord and follow others tips if it's not solve.
I was surprized that I had problems only on FGR223

**Comment by AlCalzone** [comment]
> I was surprized that I had problems only on FGR223

You are having problems with other devices too, just not as severe.

**Comment by WorldOfGZ** [comment]
Thanks it’s working better now. 
sorry, last question !
It is considered as normal that all my motion sensor Fibaro FGMR-001 have in graph a speed at 9kbps, when there is a jump ?
When no jump link is green, but when there is a jump the color is brown even if the node in middle is green with the controler.

**Comment by AlCalzone** [comment]
That means the connection between the repeater and the target node is **likely** bad.

Or this is now outdated information, but the controller keeps using the slow route until there's a need to change.
You can try doing a single node heal for the problematic ones, hoping it will result in a better route.

**Comment by WorldOfGZ** [comment]
Ok, really thanks for your help. 
I did a complete heal on all nodes but still have the 9kbps on battery modules with jump, even if middle node have 100kbps road to controller. 
but in all of case everything seems works well and I have no more dead/alive message. No wake up message also.
