### ISSUE TITLE
zwave 800 recognized as zwave 700

### ISSUE THREAD

**Issue by zeev-mindali** [AlCalzone/node-zwave-js#6699]
Dear all,

i bought a z wave 800 dev kit from silicon labs.
but when i run the zwave js ui , it recognizing it as 700 series, fw 7.18.0

i checked on silabs pc controller, and it recognized as zwave 800

what am i missing here?

**Comment by kpine** [comment]
The name is just string in a [database](https://github.com/zwave-js/node-zwave-js/blob/4229045c84c6c38676c94ec0f3f66ce6f69e516b/packages/config/config/devices/0x0000/700_series_controller.json#L5). SiLabs 700 and 800 controllers use the same IDs, the name was created before 800 was released. It should probably be updated, but that's for [node-zwave-js](https://github.com/zwave-js/node-zwave-js) to fix.

There is zero impact on functionality due to the naming. All functionality is discovered dynamically.

PC Controller is reporting the chip type, which can be seen in the Z-Wave JS driver log. "EFR32ZG23 / ZGM230S" are 800-series chips.

```text
2024-03-19T05:42:30.593Z CNTRLR   received additional controller information:                                                                                                                                                
                                    Z-Wave API version:         1 (official)                                                                                                                                                 
                                    Z-Wave chip type:           EFR32ZG23 / ZGM230S                                                                                                                                          
                                    node type                   Controller                                                                                                                                                   
                                    controller role:            primary                                                                                                                                                      
                                    controller is the SIS:      true                                                                                                                                                         
                                    controller supports timers: false
                                    nodes in the network:       1, 2, 3  
```

**Comment by zeev-mindali** [comment]
tnx a lot for the answer :) very appreciated.
i will try to update the fw as well
