### ISSUE TITLE
nvmedit: support ZWLR files

### ISSUE THREAD

**Issue by AlCalzone** [AlCalzone/node-zwave-js#6778]

**Comment by foxxcomm** [comment]
@AlCalzone --

Just tried NVM Backup of a ZAC93 controller and NVM restore to a second identical ZAC93 controller. Got no errors but the restored ZAC93 is missing all ZWLR nodes. Assume this is because ZWLR is not yet implemented in NVM backup/restore correct?

If not, let me know and I'll open an issue.

Thanks

**Comment by AlCalzone** [comment]
That's likely the reason. You should be able to skip the compatibility check to get around this.

**Comment by foxxcomm** [comment]
@AlCalzone --

Ok Thanks. When I see you merge  ZWLR NVM support I'll test again. No big deal at the moment as I only have some test nodes using ZWLR and they are performing wonderfully! Kudos!

Thanks
